### ISSUE TITLE
Non Array Error on open and file open

### ISSUE THREAD

**Issue by fferguson** [mschuchard/linter-ansible-syntax#2]
The following error is shown every time I open atom or a new file. 

This package is actually throwing the error:

[https://github.com/steelbrain/linter](url)

![screenshot from 2017-03-14 14-15-26](https://cloud.githubusercontent.com/assets/26222166/23904837/306abd22-08c1-11e7-9148-9512b75d65c2.png)

**Comment by mschuchard** [comment]
Can you provide information about your environment (versions, OS, etc.)?

**Comment by fferguson** [comment]
Ubuntu - 16.04
Ansible - 2.2.1.0
Atom - 1.14.4

Atom Packages:

- language-ansible 0.2.1 [https://github.com/haad/language-Ansible](url)

- linter 2.1.0 [https://github.com/mschuchard/linter-ansible-syntax/issues/url](url)

- linter-ansible-syntax 1.1.2

- linter-ansible-linting 1.2.2

**Comment by btito** [comment]
same here. OSX 10.12.3, ansible 2.2.1.0 installed via pip and all packages up-to-date. linter-ansible-linting works fine.

**Comment by fferguson** [comment]
I can confirm this also started happening for me after upgrade

**Comment by mschuchard** [comment]
Ok, opened an issue for this.

**Comment by mschuchard** [comment]
Oh hell, you are right. I have another linter consumer doing something similar so this will be a problem for that one also. I was making a false assumption about the `return` type, `return` scope, and Linter API in these cases.

Thanks yet again @Arcanemagus for figuring out what was going on.

Everyone else: will roll out a fix for this hopefully shortly.

**Comment by mschuchard** [comment]
Fixed in 98fdd988cb4487f6e40bd9b489c2e420ec8a8447 and verified working with Linter 2.1.0. Rolling out hotfix release shortly.

**Comment by btito** [comment]
Great, Thanks!

fix online and working here!
