### ISSUE TITLE
new ansible version issue 

### ISSUE THREAD

**Issue by admin4ek** [mschuchard/linter-ansible-syntax#5]
Hello,

I've updated the ansible version to ansible 2.2.2.0 and got the following error:

`An unexpected error with ansible, ansible-lint, linter-ansible-linting, atom, linter, and/or your playbook, has occurred.`
Could you please help me to resolve this issue.

Thanks,

**Comment by mschuchard** [comment]
Atom gives a more detailed output for your error underneath that. What is the information displayed there?
