### ISSUE TITLE
Please support source.ansible-advanced

### ISSUE THREAD

**Issue by brandonkal** [mschuchard/linter-ansible-syntax#6]
I noticed this package was not linting with ansible-advanced from language-ansible.
There is no mention that this would be the case. Changing to source.ansible got the linter to fire.
If this package supported ansible-advanced syntax that would be best. Thank you.

**Comment by mschuchard** [comment]
I can look into this for both Ansible linter packages.

**Comment by mschuchard** [comment]
Added in e58110a for this package. Included in new release v1.2.1 for this package and v1.3.3 for ansible-lint package.
