### ISSUE TITLE
detection of ansible version is broken

### ISSUE THREAD

**Issue by larsf** [mschuchard/linter-ansible-syntax#7]
currently you check for the ansible version being greater than 2.0 as follows:

49       if (/1\.\d+\.\d+/.exec(output)) {

that does no work when the output of ansible-playbook --version is as follows:

ansible-playbook 2.8.4
  config file = None
  configured module search path = ['/Users/lfredriksen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.4/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]

because the regex you have will match on clang-1001.0.46

suggest you agment the regex to something like:
if (/ansible-playbook 1\.\d+\.\d+/.exec(output)) {

**Comment by mschuchard** [comment]
The version check was improved to be more accurate in a recent commit. It will be reflected in the next release.

**Comment by walterrowe** [comment]
When will this be released? It is still broken 9 months later?
