### ISSUE TITLE
Fails to parse dynamic-inventory

### ISSUE THREAD

**Issue by serpro69** [mschuchard/linter-ansible-syntax#8]
If I include the dynamic inventory script in the settings I'm getting that it failed to parse the inventory file and only implicit localhost is available.
Removing the inventory setting altogether naturally throws a null pointer.
Is there a workaround for this to use this package with dynamic inventories or disable parsing the inventory (if the rest of the functionality is not dependent on this)?

**Comment by serpro69** [comment]
Setting this to `/etc/ansible/hosts` helped resolve this issue and a few others (for example incorrect line numbers displayed for lint issues)

**Comment by mschuchard** [comment]
Hi, are you still having this issue? If so, can you provide a MCVE of the dynamic inventory for me to test against?

**Comment by serpro69** [comment]
Hi.
I haven't tried using the plug-in with the dynamic inventory since. But I will try to reproduce it and provide you with the inventory script.

**Comment by mschuchard** [comment]
No reply; closing.
